### ISSUE TITLE
¿Webpack?

### ISSUE THREAD

**Issue by alelopez07** [horchatajs/charlas#1]
Últimamente he visto un poco sobre Webpack module bundler de hecho, observé que instagram lo utiliza en su interfaz web, se me haría un poco interesante encontrar a alguien que ya se haya introducido en esto para saber mejor sobre su funcionamiento y hacia donde le apunta.

**Comment by leosuncin** [comment]
Si aún tienen curiosidad sobre Webpack yo puedo dar una charla, no soy un experto pero lo se usar sin morir en el intento

**Comment by ricardoerl** [comment]
@leosuncin ¡Chivo! te anoto entonces.

**Comment by leosuncin** [comment]
Si puedo dar la charla
