### ISSUE TITLE
Introducción a Redis

### ISSUE THREAD

**Issue by masmerino13** [horchatajs/charlas#11]
En la actualidad Redis es (según Amazon) el almacén de valores de clave más popular en la actualidad.

Gracias a su velocidad y facilidad de uso, Redis es una opción popular para aplicaciones web, móviles, de juegos, de tecnología publicitaria y de IoT que requieren el mejor desempeño de su clase.

Seria genial una introducción de casos de uso y experiencias.

**Comment by LuisMejiaF** [comment]
Hola colegas. Me gustaría proponerme como ponente para esta charla. Ya he trabajado en un par de proyectos sencillos con REDIS, y creo que puedo dar una introducción a este key-value storage.

**Comment by cesaramirez** [comment]
Que tal @LuisMejiaF tienes disponibilidad para el evento de Junio para impartir la charla?

**Comment by LuisMejiaF** [comment]
Claro. Sólo háganme saber la fecha y yo hago espacio para ése día.

**Comment by cesaramirez** [comment]
El evento sera el sábado 30 de Junio, si te animas te pediría el favor de crear un nuevo issue detallando el tema y descripción de la charla

**Comment by cesaramirez** [comment]
Me confirmas @LuisMejiaF si estas disponible y dejamos la charla confirmada para el evento de Junio, por favor si no estas en slack Unete para comunicarnos por ahi. http://slack.horchatajs.com

**Comment by LuisMejiaF** [comment]
Confirmado. Voy a crear el otro issue entonces.

**Comment by cesaramirez** [comment]
Perfecto y gracias 👍

**Comment by cesaramirez** [comment]
Asociado a issue #27
