### ISSUE TITLE
Node on Sails: Una Introducción a SailsJS

### ISSUE THREAD

**Issue by davmrv** [horchatajs/charlas#12]
# Node on Sails: Una Introducción a SailsJS

Una pequeña charla de cómo comenzar a desarrollar utilizando el popular framework **SailsJS**.

SailsJS es un **framework** que está ganando potencia en la comunidad
de desarrolladores que utilizan **NodeJS**, así que es de bastante utilidad
conocer sus ventajas como también sus desventajas, saber cuando es útil
y cuando puede estar de más para tu proyecto.

Por su flexibilidad y potencia, es un herramienta que puede ayudarte a
desarrollar con gran velocidad sin tener que preocuparte mucho por
la configuración del framework ni la implementación de diferentes
herramientas para un proyecto, ya que **SailsJS** se encarga de proveer
al desarrollador con todo lo necesario para empezar el desarrollo en poco
tiempo.

Además, más que ser una charla sobre el framework, planea poder ser una charla
sobre buenas prácticas en el desarrollo de aplicaciones, al menos en lo que sea posible
compartir (puede crearse otra charla sobre estandares y buenas prácticas de aún no existir).

**Comment by ricardoerl** [comment]
Me parece bien @Bl4ckf4ll, el tema de buenas prácticas en general merece un evento por si solo, pero para este tema me gusta la idea que compartas tu experiencia y consejos usando SailsJS.
