### ISSUE TITLE
Introducción a las diferentes web APIs

### ISSUE THREAD

**Issue by Ciensprog** [horchatajs/charlas#14]
Hay muchas APIs disponibles para utilizar en los diferentes proyectos web, entre ellas se encuentran Offline, Vibration, PageVisibility, etc... Los puntos a tomar en cuenta son:

- Los usos en los proyectos donde se requiera implementar.
- Librerías para mejor compatibilidad.

Pueden ser de mucha utilidad para nuestras apps, ya que nos permitirían tener una mejor experiencia de usuario (UX) dando un toque extra de interacción para que los usuarios tengan un poco más de curiosidad en la misma.

**Ponente**: [Leo López](https://github.com/Ciensprog)
**Tipo**: larga duración (40 minutos)

**Comment by cesaramirez** [comment]
Gracias por la propuesta @Ciensprog, ¿Estarías con disponibilidad para dar la charla en el evento de Abril?

**Comment by Ciensprog** [comment]
Por supuesto @cesaramirez con mucho gusto.
