### ISSUE TITLE
Dockerizando una Aplicación de Node.js

### ISSUE THREAD

**Issue by jrab66** [horchatajs/charlas#16]
Charla enfocada a empezar al desarrollo de aplicaciones aprovechando el recurso de **Docker**.

Se abordara una intro básica a **docker** y como este puede presentar una gran herramienta a la hora de hacer desarrollo tanto local como en equipos, para luego mostrar como empaquetar una aplicación **nodejs** en el.

El objetivo de la charla es:

- Fomentar la adopción y  uso de docker 
- Descripción de como Crear un Dockerfile sencillo.
- Mostrar ventajas tanto para desarrollo como para producción.

**Ponente**: Jose Barahona
**Tipo**: larga duración (40 minutos)

**Comment by cesaramirez** [comment]
Muchas gracias @jrab66 por la propuesta, ¿estarías disponible para dar le charla en el evento de Abril?

**Comment by jrab66** [comment]
Si, tengo disponibilidad de tiempo @cesaramirez
