### ISSUE TITLE
Testing con JavaScript

### ISSUE THREAD

**Issue by barbunzel** [horchatajs/charlas#17]
Propongo la siguiente charla y también me propongo como ponente:

Una charla enfocada a las prácticas de testing, test-driven development, unit testing y e2e; un poco de las frameworks que existen para cada cosa, charlar un poco de todo esto, mi experiencia (y la de algunas personas que conozco) y lo más importante, un demo de unit testing y de e2e (por el momento lo he pensado con mocha o jest para unit tests, y testcafe para e2e).

**Comment by cesaramirez** [comment]
Muchas gracias por la propuesta @dieguito151, ¿Estarías en la disponibilidad de de dar la charla para el evento de Abril?

**Comment by barbunzel** [comment]
Sí, ¡claro!

**Comment by ragar90** [comment]
Ya se dio esta charla?

**Comment by barbunzel** [comment]
Todavía no.

**Comment by cesaramirez** [comment]
Creo que lo que pregunta @ragar90 es con relación a que en marzo se dio una charla en la Don Bosco con respecto a este tema.

**Comment by cesaramirez** [comment]
Hola @dieguito151 en los eventos pasados se ha dado charla de testing sobre todo enfocado en unit testing, seria interesante enfocar esta con el tema de e2e no se que te parece, estas disponible para el evento de junio?

**Comment by barbunzel** [comment]
Perdón por contestar tarde. Ando de viaje y no estaré en El Salvador por un tiempo. Con gusto puede ser de e2e nada más, pero tendría que ser en el de agosto, a menos que alguien más se anime a dar una charla de esto. 😁

**Comment by cesaramirez** [comment]
Hola @dieguito151, ¿Podemos retomar estar charla siempre con e2e, para el primer evento de año?

**Comment by barbunzel** [comment]
¡Perdón! Acabo de ver esto. Hace un par de días vi el evento de Horchata, pero si todavía hay espacio, claro que sí. :)

**Comment by cesaramirez** [comment]
Claro que hay espacio, hablemos por Slack para darte mas detalles.

**Comment by barbunzel** [comment]
¡Claro que sí!
