### ISSUE TITLE
AWS y serverless

### ISSUE THREAD

**Issue by sergioadonis** [horchatajs/charlas#19]
**Título:**
Amazon Web Services

**Descripción:**
Servicios que ofrece Amazon Web Services (AWS), como aprovecharlos, y como simplificar las operaciones con el enfoque de serverless.

**Ponente:**

**Email (si no está en el perfil de github):**

**Tipo:** lightning talk (15 minutos) | corta duración (25 minutos) | larga duración (40 minutos)

**Comment by cesaramirez** [comment]
Gracias por la propuesta @sergioadonis, seria interesante ver una charla orientada a hacer serveless con una aplicación de React, Vue ó Node.

**Comment by sergioadonis** [comment]
Sí, sería muy interesante una demo con funciones lambda con nodejs y una app react que complemente... Quizás no alcancen 40 minutos jaja

**Comment by cesaramirez** [comment]
@glopez97 sera el ponente de esta charla para nuestro evento de agosto.
