### ISSUE TITLE
Deploy de una aplicación Node.js en producción

### ISSUE THREAD

**Issue by leosuncin** [horchatajs/charlas#20]
**Título:** Deploy de una aplicación Node.js en DigitalOcean

**Descripción:** El proceso de cómo crear un VPS en DigitalOcean y prepararlo para ejecutar una aplicación Node.js utilizando Docker, siguiendo buenas prácticas de CI/CD

**Ponente:** Jaime Leonardo Suncin Cruz

**Tipo:** larga duración (30 minutos)

**Comment by cesaramirez** [comment]
Muy interesante propuesta @leosuncin, ¿estarías disponible dar la charla para el evento de Junio?

**Comment by leosuncin** [comment]
Si ya no me alcanzo a colar en la de Abril, puedo hacerlo en Junio

**Comment by cesaramirez** [comment]
Entonces quedamos para Junio, para el evento de Abril ya definimos las charlas a impartir.

**Comment by cesaramirez** [comment]
Hola @leosuncin aun estas disponible para el evento de Junio para dar la charla?

**Comment by leosuncin** [comment]
Si, ¿cuando sera el próximo HorchataJS?

**Comment by cesaramirez** [comment]
El Sabado 30 de Junio.
