### ISSUE TITLE
Strapi

### ISSUE THREAD

**Issue by sergioadonis** [horchatajs/charlas#21]
**Título:**
Strapi - Node.js REST API Framework with extensible Admin Panel.
[Strapi.io](https://strapi.io/)

**Descripción:**
Strapi es un framework de nodejs basado en Koa, que a su vez está basado en Express, además es bastante similar a Sails.

Lo peculiar de Strapi es que tiene un panel de administrador, similar al de Django, o de Laravel-Voyager, donde se puede hacer en mantenimiento de las tablas de tu base de datos, gestionar permisos, incluso crear tus tablas desde ahí.

Sería interesando una charla acerca de este framework.

**Ponente:**

**Email (si no está en el perfil de github):**

**Tipo:** lightning talk (15 minutos) | corta duración (25 minutos) | larga duración (40 minutos)

**Comment by cesaramirez** [comment]
Gracias por la propuesta @sergioadonis he leído sobre este framework, se leen cosas interesantes, ojalá alguien se anime a hablar un poco de él.

**Comment by davmrv** [comment]
Yo estoy usando **strapi** en unos proyectos que tengo ahorita, así que estoy viendo un puño de ondas super geniales, así que si no se encuentra a alguien más que hable de esto pues me gustaría ver si puedo dar una plática sobre esto en alguna horchataJS próxima :smile:

**Comment by cesaramirez** [comment]
Pues si te animas te dejamos programado para el evento de agosto

**Comment by davmrv** [comment]
Demole entonces @cesaramirez

**Comment by cesaramirez** [comment]
@Bl4ckf4ll Siempre contamos con tu charla para el evento de agosto?
