### ISSUE TITLE
Estructuras de datos y algoritmos con JS

### ISSUE THREAD

**Issue by ragar90** [horchatajs/charlas#22]
**Título:** Estructuras de datos y algoritmos con JS

**Descripción:** Fundamentos de algoritmos computacionales y aplicaciones

**Ponente:** Rene Garcia @ragar90

**Email:** rene.garciah90@gmail.com

**Tipo:** larga duración (40 minutos)

**Comment by cesaramirez** [comment]
¿Que tal @ragar90 estas disponible para dar la charla en el evento de agosto?

**Comment by ragar90** [comment]
si puedo darla, cuando es el evento?

**Comment by cesaramirez** [comment]
El evento es el 25 de agosto.

**Comment by ragar90** [comment]
chivisimo puedo preparala para esa fecha

**Comment by cesaramirez** [comment]
Perfecto entonces ya estas confirmado y nos estamos comunicando por Slack para futuros detalles.

**Comment by ragar90** [comment]
chivisimo reservo la fecha entonces
