### ISSUE TITLE
Husky a guide dog for Git Hooks

### ISSUE THREAD

**Issue by alepaz** [horchatajs/charlas#23]
**Husky a guide dog for Git Hooks:**

**[Git Hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks):** Git has a way to trigger custom scripts when certain important actions occur, although client-side hooks are not copied when you clone a repository; but there is a way to take advantage of this feature.

-What is a Git Hook
-Client-Side Hooks
-Server-Side Hooks
-what is Husky?
-what is Commitizen?
-Git hook to avoid commits without format
-Git hook to avoid commits who break Jest unit testings

**Ponente:** Alejandro Paz

**Tipo:** larga duración (30 minutos)

**Comment by cesaramirez** [comment]
Hola @alepaz, ¿Estas disponible para poder dar esta charla en el primer evento del año?

**Comment by ricardoerl** [comment]
Hola @alepaz, estamos revisando nuevamente las charlas y queremos ver si ¿todavía te animas a dar está charla?. Estamos pensando en noviembre 2019.

**Comment by alepaz** [comment]
Claro @ricardoerl sería un honor participar, ¿no hay problema si la presentación fuera remota?
