### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by aledevme** [horchatajs/charlas#25]
**Título:**
Manejo Basico de MongoDb
**Descripción:**
Consultas 
**Ponente: **
Alejandro Gonzalez
**Email (si no está en el perfil de github):**

**Tipo:** corta duración (25 minutos)

>

**Comment by cesaramirez** [comment]
Hola @DevAlex7 la charla de mongoDB básico ya se dio en un charla pasada, seria ideal en este caso hablar de temas mas avanzados.

**Comment by ricardoerl** [comment]
Hola @DevAlex7, ¿algún tema en especifico que te interese sobre MongoDB? Anteriormente tocamos la introducción pero creo que hay oportunidad de extender el tema.

**Comment by aledevme** [comment]
mmmm, me quedo con "Introducción a Laravel
"
