### ISSUE TITLE
Introducción a NativeScript

### ISSUE THREAD

**Issue by hugogilmar** [horchatajs/charlas#29]
Introducción a NativeScript

NativeScript es un framework para desarrollar aplicaciones en Apple iOS y Android. Las aplicaciones NativeScript se construyen utilizando Javascript o TypeScript. Tiene implementaciones para Angular y VueJS aunque también se puede trabajar con Vanilla JS.

**Comment by Anb98** [comment]
Me propongo como ponente.

**Comment by ricardoerl** [comment]
Hola @hugogilmar, @Anb98 estamos revisando nuevamente las charlas y queremos ver si ¿todavía alguno se anima a dar está charla?. Estamos pensando en noviembre 2019.

**Comment by Anb98** [comment]
> Hola @hugogilmar, @Anb98 estamos revisando nuevamente las charlas y queremos ver si ¿todavía alguno se anima a dar está charla?. Estamos pensando en noviembre 2019.

Claro! cuál sería el proceso a seguir?
