### ISSUE TITLE
Trabajo remoto. Quiero uno, ¿cómo lo consigo y qué significa trabajar así?

### ISSUE THREAD

**Issue by eduarmreyes** [horchatajs/charlas#34]
**Título:**
Trabajo remoto. Quiero uno, ¿cómo lo consigo y qué significa trabajar así?

**Descripción:**
La idea es demostrar lugares donde podemos encontrar trabajo remoto, también explicar qué significa tributariamente tener un trabajo así y no regarla a la hora de buscar préstamos, tener problemas de salud y eso.

También tips para no morir en el intento y no perder el tiempo, sino trabajar de verdad.

**Ponente:**
@eduarmreyes

**Tipo:** lightning talk.

**Comment by cesaramirez** [comment]
Que ondas @eduarmreyes, ¿Te animas a dar esta charla en el primer evento del año?

**Comment by eduarmreyes** [comment]
Me tri animo, te escribo en Slack para que lleguemos a algo.

**Comment by cesaramirez** [comment]
Perfecto!
