### ISSUE TITLE
Are you Nuxt? - Introducción a NuxtJS

### ISSUE THREAD

**Issue by xdiegom** [horchatajs/charlas#40]
**Título:** Are you Nuxt? - Introducción a NuxtJS

**Descripción:** Nuxt.js es un framework para crear aplicaciones con VueJS. Podés crear tres tipos de aplicaciones: Universal, Single Page Application o Página estática.

**Ponente:** Diego Melgar

**Email (si no está en el perfil de github):**

**Tipo:** larga duración (40 minutos)

**Comment by cesaramirez** [comment]
Hola @xdiegom hemos visto interesante tu charla, estas interesado en ser ponente par el próximo evento del 28 de septiembre?

**Comment by xdiegom** [comment]
Hola @cesaramirez. Si, me apunto 🤘
