### ISSUE TITLE
Introduccion a TailwindCSS

### ISSUE THREAD

**Issue by masmerino13** [horchatajs/charlas#48]
**Título:**
Introduccion a Tailwind

**Descripción:**
Introduccion a Tailwind y su nuevo enfoque para el desarrollo front-end

**Ponente:**
Ricardo Merino @masmerino13 

**Email (si no está en el perfil de github):**

**Tipo:** lightning talk (15 minutos) | corta duración (25 minutos) | larga duración (40 minutos)
15 minutos

**Comment by cesaramirez** [comment]
@masmerino13 Tenes disponibilidad para el próximo evento, será el 27 de Julio

**Comment by masmerino13** [comment]
Si, suena bien @cesaramirez

**Comment by cesaramirez** [comment]
Eres el primer pontente confirmado, gracias @masmerino13, nos vemos el 27

**Comment by masmerino13** [comment]
:open_mouth: cool, gracias por el chance @cesaramirez !
