### ISSUE TITLE
What's Next.js? SSR sin esfuerzo

### ISSUE THREAD

**Issue by leosuncin** [horchatajs/charlas#49]
**Título:** What's Next.js? SSR sin esfuerzo

**Descripción:** Next.js es un framework para hacer Server Side Render con React sin esfuerzo, sin necesidad de configurar solo de instalar y usar. Su [última versión](https://nextjs.org/blog/next-9) permite crear APIs además de Web Apps, crear páginas estáticas y dinamicas de forma automática.

**Ponente:** Jaime Leonardo Suncin Cruz

**Email (si no está en el perfil de github):** @leosuncin

**Tipo:** corta duración (25 minutos)

**Comment by cesaramirez** [comment]
@leosuncin que ondas, te animas dar la charla para el evento del 27 de Julio?

**Comment by leosuncin** [comment]
Chivo

**Comment by cesaramirez** [comment]
Demosle entonces @leosuncin, muchas gracias.
