### ISSUE TITLE
Enough REST, think GraphQL!

### ISSUE THREAD

**Issue by mariomenjr** [horchatajs/charlas#52]
**Título:** 
Enough REST, think GraphQL!

**Descripción:** 
Una breve Introducción a la tecnología, comparativa práctica con REST, los términos y conceptos más importantes.

**Ponente:** 
Mario Menjívar Sermeño (@mariomenjr)

**Email (si no está en el perfil de github):**

**Tipo:** 
Corta duración (25 minutos)

**Comment by leosuncin** [comment]
Solo resalto que este tema ya se dio en una edición anterior de HorchataJS https://github.com/horchatajs/charlas/issues/9#issuecomment-375079215

Para tratar de hablar sobre otras cosas que nos se dieron o llevarla a un nivel más avanzado que una introducción.

**Comment by ricardoerl** [comment]
@mariomenjr como lo menciona @leosuncin, ya anteriormente abordamos una intro a GraphQL pero creo que todavía hay oportunidad de complementar el tema, ¿que te parece si se tocan buenas prácticas, optimizaciones o algun caso de uso más especifico?

**Comment by mariomenjr** [comment]
@leosuncin ¡hey! gracias por el heads-up. Seguramente pasé por alto ese item en el historial.

Claro, me daré un tiempo esta semana para ver exactamente qué podría presentar (probablemente siguiendo algo cómo lo que mencionas, "buenas prácticas" y demás), @ricardoerl. Ahí verán este issue actualizado.

**Comment by mariomenjr** [comment]
Me enfocaré en otro tema. Uno que tuve la oportunidad de hablar recientemente 😁

Ya revisé, y no, no hay ninguna entrada 😅

![image](https://user-images.githubusercontent.com/1946936/71954377-fba6ee80-3199-11ea-9450-db4ae11292d4.png)
